### ISSUE TITLE
When reading files, the file order will be messed up.

### ISSUE THREAD

**Issue by AspasiaKun** [akasaki1211/sdf_shadow_threshold_map#1]
![image](https://github.com/user-attachments/assets/b7ab8e79-8981-4a0e-aa59-671fd7ad430c)
It appears in my mac. I think some sorting rules could be added maybe ？

**Comment by akasaki1211** [comment]
Thanks for letting me know.
It looks like I forgot to include the sorting. I'll fix it ASAP.

**Comment by akasaki1211** [comment]
Fixed in commit f03cb0e7dc8cbeaf330f0c401a48f4bbca8ece98. Release version is [`0.3.1`](https://github.com/akasaki1211/sdf_shadow_threshold_map/releases/tag/0.3.1)

**Comment by AspasiaKun** [comment]
LGTM. Thanks.
